///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyWebTest6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyWebTest6Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6481fca6-812c-4c09-a56b-4fe74bcb3a36")]
    public partial class MyWebTest6Repository : RepoGenBaseFolder
    {
        static MyWebTest6Repository instance = new MyWebTest6Repository();
        MyWebTest6RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyWebTest6RepositoryFolders.NewTabGoogleChromeAppFolder _newtabgooglechrome;
        MyWebTest6RepositoryFolders.NewTabAppFolder _newtab;

        /// <summary>
        /// Gets the singleton class instance representing the MyWebTest6Repository element repository.
        /// </summary>
        [RepositoryFolder("6481fca6-812c-4c09-a56b-4fe74bcb3a36")]
        public static MyWebTest6Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyWebTest6Repository() 
            : base("MyWebTest6Repository", "/", null, 0, false, "6481fca6-812c-4c09-a56b-4fe74bcb3a36", ".\\RepositoryImages\\MyWebTest6Repository6481fca6.rximgres")
        {
            _applicationundertest = new MyWebTest6RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _newtabgooglechrome = new MyWebTest6RepositoryFolders.NewTabGoogleChromeAppFolder(this);
            _newtab = new MyWebTest6RepositoryFolders.NewTabAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6481fca6-812c-4c09-a56b-4fe74bcb3a36")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("ab45d332-106c-40d8-89c2-7f233816ce0f")]
        public virtual MyWebTest6RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The NewTabGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("94fd398d-45d7-4ffd-810f-9988077189e3")]
        public virtual MyWebTest6RepositoryFolders.NewTabGoogleChromeAppFolder NewTabGoogleChrome
        {
            get { return _newtabgooglechrome; }
        }

        /// <summary>
        /// The NewTab folder.
        /// </summary>
        [RepositoryFolder("454133cd-f970-4022-82bc-6890c49c020b")]
        public virtual MyWebTest6RepositoryFolders.NewTabAppFolder NewTab
        {
            get { return _newtab; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyWebTest6RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("ab45d332-106c-40d8-89c2-7f233816ce0f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _requestademoInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "ab45d332-106c-40d8-89c2-7f233816ce0f", "")
            {
                _requestademoInfo = new RepoItemInfo(this, "RequestADemo", ".//div[#'et_builder_outer_content']/div/div[1]/div/div/div[2]/a[@innertext='Request a demo']", "", 30000, null, "2a9113cb-d29e-4288-b0db-4bace2b9d410");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ab45d332-106c-40d8-89c2-7f233816ce0f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ab45d332-106c-40d8-89c2-7f233816ce0f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RequestADemo item.
            /// </summary>
            [RepositoryItem("2a9113cb-d29e-4288-b0db-4bace2b9d410")]
            public virtual Ranorex.ATag RequestADemo
            {
                get
                {
                    return _requestademoInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RequestADemo item info.
            /// </summary>
            [RepositoryItemInfo("2a9113cb-d29e-4288-b0db-4bace2b9d410")]
            public virtual RepoItemInfo RequestADemoInfo
            {
                get
                {
                    return _requestademoInfo;
                }
            }
        }

        /// <summary>
        /// The NewTabGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("94fd398d-45d7-4ffd-810f-9988077189e3")]
        public partial class NewTabGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addressandsearchbarInfo;

            /// <summary>
            /// Creates a new NewTabGoogleChrome  folder.
            /// </summary>
            public NewTabGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewTabGoogleChrome", "/form[@title='New Tab - Google Chrome']", parentFolder, 30000, null, true, "94fd398d-45d7-4ffd-810f-9988077189e3", "")
            {
                _addressandsearchbarInfo = new RepoItemInfo(this, "AddressAndSearchBar", "container[@accessiblename='New Tab - Google Chrome']/container[@accessiblename='Google Chrome']/container[2]/container[1]/toolbar[1]/?/?/text[@accessiblename='Address and search bar']", "", 30000, null, "9ed54845-2436-41a8-81b1-1f3fa1620776");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("94fd398d-45d7-4ffd-810f-9988077189e3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("94fd398d-45d7-4ffd-810f-9988077189e3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item.
            /// </summary>
            [RepositoryItem("9ed54845-2436-41a8-81b1-1f3fa1620776")]
            public virtual Ranorex.Text AddressAndSearchBar
            {
                get
                {
                    return _addressandsearchbarInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item info.
            /// </summary>
            [RepositoryItemInfo("9ed54845-2436-41a8-81b1-1f3fa1620776")]
            public virtual RepoItemInfo AddressAndSearchBarInfo
            {
                get
                {
                    return _addressandsearchbarInfo;
                }
            }
        }

        /// <summary>
        /// The NewTabAppFolder folder.
        /// </summary>
        [RepositoryFolder("454133cd-f970-4022-82bc-6890c49c020b")]
        public partial class NewTabAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new NewTab  folder.
            /// </summary>
            public NewTabAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewTab", "/dom[@domain='newtab']", parentFolder, 30000, null, false, "454133cd-f970-4022-82bc-6890c49c020b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("454133cd-f970-4022-82bc-6890c49c020b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("454133cd-f970-4022-82bc-6890c49c020b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
