///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyWebTest6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("d2a7c68e-f398-4cd3-832d-4de6f86f8892", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyWebTest6Repository repository.
        /// </summary>
        public static MyWebTest6Repository repo = MyWebTest6Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Alt+Tab' Press.", new RecordItemIndex(0));
            Keyboard.Press(System.Windows.Forms.Keys.Tab | System.Windows.Forms.Keys.Alt, 15, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NewTabGoogleChrome.AddressAndSearchBar' at 634;11.", repo.NewTabGoogleChrome.AddressAndSearchBarInfo, new RecordItemIndex(1));
            repo.NewTabGoogleChrome.AddressAndSearchBar.Click("634;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ra' with focus on 'NewTabGoogleChrome.AddressAndSearchBar'.", repo.NewTabGoogleChrome.AddressAndSearchBarInfo, new RecordItemIndex(2));
            repo.NewTabGoogleChrome.AddressAndSearchBar.PressKeys("ra");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}{Return}' with focus on 'NewTabGoogleChrome.AddressAndSearchBar'.", repo.NewTabGoogleChrome.AddressAndSearchBarInfo, new RecordItemIndex(3));
            repo.NewTabGoogleChrome.AddressAndSearchBar.PressKeys("{Right}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RequestADemo' at 117;13.", repo.ApplicationUnderTest.RequestADemoInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RequestADemo.Click("117;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
